"""
Elasticsearch index management for the b-roll corpus.

Embeddings are generated by the Jina API (jina-embeddings-v5-omni-small)
before indexing — the visual encoder is active there, unlike the EIS
pre-configured endpoint which treats all input as text.

Vectors are stored as dense_vector (cosine similarity) and searched via kNN.

Index naming convention: `broll-{strategy}-{quant}`
  e.g.  broll-scene-float32   (float32 HNSW, baseline)
        broll-scene-int8       (int8 quantization, ~4× smaller)
        broll-scene-int4       (int4 quantization, ~8× smaller)
        broll-scene-bbq        (binary quantization, ~32× smaller)
"""

from __future__ import annotations
import os
from dataclasses import asdict, dataclass, field
from typing import Iterable, Optional

from elasticsearch import Elasticsearch, helpers


@dataclass
class ChunkDoc:
    """One indexable record."""
    chunk_id: str
    clip_id: str
    path: str
    start_sec: float
    end_sec: float
    duration: float
    strategy: str
    # Metadata for hybrid search / filtering
    uploaded_at: str        # ISO date
    uploader: str
    tags: list
    transcript: Optional[str]   # STT output — feeds BM25 in hybrid search
    embedding: list             # 1024-d Jina float vector


def es_client() -> Elasticsearch:
    kwargs: dict = {"request_timeout": 120}
    api_key = os.environ.get("ES_API_KEY")
    if api_key:
        kwargs["api_key"] = api_key
    return Elasticsearch(os.environ["ES_URL"], **kwargs)


# Maps CLI/UI index_type token → (ES index_options type, short label for index name)
_INDEX_TYPES: dict[str, str] = {
    "hnsw":      "float32",  # float32 HNSW baseline
    "int8_hnsw": "int8",     # 4× smaller, ~same recall     (ES ≥ 8.12)
    "int4_hnsw": "int4",     # 8× smaller, small recall hit (ES ≥ 8.15)
    "bbq_hnsw":  "bbq",      # 32× smaller, binary quant    (ES ≥ 8.16)
}


def index_name(strategy: str, index_type: str = "hnsw", dims: int = 1024) -> str:
    label = _INDEX_TYPES.get(index_type, index_type)
    return f"broll-{strategy}-{dims}d-{label}"


def create_index(es: Elasticsearch, name: str, dims: int = 1024,
                 index_type: str = "hnsw") -> None:
    """Create index with a dense_vector field for kNN search.

    index_type controls HNSW quantization:
        hnsw      — float32, default
        int8_hnsw — scalar int8  (ES ≥ 8.12)
        int4_hnsw — scalar int4  (ES ≥ 8.15)
        bbq_hnsw  — binary quant (ES ≥ 8.16)
    """
    if es.indices.exists(index=name):
        return

    mappings = {
        "properties": {
            "chunk_id":    {"type": "keyword"},
            "clip_id":     {"type": "keyword"},
            "path":        {"type": "keyword", "index": False},
            "start_sec":   {"type": "float"},
            "end_sec":     {"type": "float"},
            "duration":    {"type": "float"},
            "strategy":    {"type": "keyword"},
            "uploaded_at": {"type": "date"},
            "uploader":    {"type": "keyword"},
            "tags":        {"type": "keyword"},
            "transcript":  {"type": "text", "analyzer": "english"},
            "embedding": {
                "type":          "dense_vector",
                "dims":          dims,
                "index":         True,
                "similarity":    "cosine",
                "index_options": {"type": index_type},
            },
        }
    }
    es.indices.create(index=name, mappings=mappings)
    print(f"Created index '{name}' ({dims}-d cosine {index_type})")


def bulk_index(es: Elasticsearch, name: str, docs: Iterable[ChunkDoc]) -> int:
    """Bulk-index all docs. Embeddings are already computed — no inference
    calls happen here, so standard helpers.bulk is fast and reliable."""
    actions = (
        {"_index": name, "_id": d.chunk_id, "_source": asdict(d)}
        for d in docs
    )
    success, errors = helpers.bulk(es, actions, raise_on_error=False)
    if errors:
        print(f"⚠ {len(errors)} bulk indexing errors")
        for e in errors[:3]:
            print(f"  {e}")
    return success


def knn_search(
    es: Elasticsearch,
    index: str,
    query_vector: list[float],
    k: int = 10,
    num_candidates: int = 100,
    filter_clauses: Optional[list[dict]] = None,
) -> list[dict]:
    """Pure kNN search over the dense_vector embedding field."""
    knn: dict = {
        "field":        "embedding",
        "query_vector": query_vector,
        "k":            k,
        "num_candidates": num_candidates,
    }
    if filter_clauses:
        knn["filter"] = {"bool": {"filter": filter_clauses}}

    res = es.search(
        index=index,
        knn=knn,
        size=k,
        source_excludes=["embedding"],
    )
    return [
        {**hit["_source"], "_score": hit["_score"]}
        for hit in res["hits"]["hits"]
    ]


# Keep semantic_search as an alias so backend.py import doesn't break
def semantic_search(
    es: Elasticsearch,
    index: str,
    query_vector: list[float],
    k: int = 10,
    filter_clauses: Optional[list[dict]] = None,
) -> list[dict]:
    return knn_search(es, index, query_vector, k=k, filter_clauses=filter_clauses)


def hybrid_search(
    es: Elasticsearch,
    index: str,
    query_text: str,
    query_vector: list[float],
    k: int = 10,
    filter_clauses: Optional[list[dict]] = None,
) -> list[dict]:
    """RRF fusion of BM25 over transcript + kNN over visual embedding."""
    filters = filter_clauses or []

    knn_retriever = {
        "knn": {
            "field": "embedding",
            "query_vector": query_vector,
            "k": k,
            "num_candidates": k * 5,
            **({"filter": {"bool": {"filter": filters}}} if filters else {}),
        }
    }
    bm25_retriever = {
        "standard": {
            "query": {
                "bool": {
                    "must": [{"match": {"transcript": query_text}}],
                    **({"filter": filters} if filters else {}),
                }
            }
        }
    }

    res = es.search(
        index=index,
        size=k,
        source_excludes=["embedding"],
        retriever={
            "rrf": {
                "retrievers": [knn_retriever, bm25_retriever],
                "rank_window_size": 50,
                "rank_constant": 60,
            }
        },
    )
    return [
        {**hit["_source"], "_score": hit["_score"]}
        for hit in res["hits"]["hits"]
    ]
